#
# ~/.bash_profile
#

# Git agent
[[ -z "$SSH_AUTH_SOCK" ]] && eval $(ssh-agent -s)

if [[ -z $DISPLAY ]] && [[ $(tty) = /dev/tty1 ]] && command -v startx; then
    exec startx
fi

[[ -f ~/.bashrc ]] && . ~/.bashrc
