theme = "nightfox"

[editor]
true-color = true
#rulers = [81]
bufferline = "multiple"
color-modes = true

[editor.statusline]
left = ["mode", "spinner", "file-name", "file-type", "file-encoding"]
right = ["diagnostics", "selections", "position", "position-percentage", "total-line-numbers"]


[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.soft-wrap]
enable = true

[keys.normal]
C-l = "jump_view_right"
C-h = "jump_view_left"
C-k = ["scroll_up", "scroll_up", "scroll_up"]
C-j = ["scroll_down", "scroll_down", "scroll_down"]
