#!/usr/bin/bash

BACKLIGHT="intel_backlight"
UNIQUE_ID=100299
APP=Backlight

max=$(cat /sys/class/backlight/$BACKLIGHT/max_brightness)
actual=$(cat /sys/class/backlight/$BACKLIGHT/actual_brightness)

echo $max
echo $actual


if [[ $1 == "-i" ]]; then
	if [[ actual -lt $((max * 10 / 100)) ]]; then
		percentage=2
	elif [[ actual -lt $((max * 30 / 100)) ]]; then
		percentage=5
	else
		percentage=10
	fi

	step=$((max * percentage / 100))
	inc=$((actual + step))
	if [[ $inc -ge $max ]]; then
		inc=$max
	fi
	echo $inc > /sys/class/backlight/$BACKLIGHT/brightness
	new=$(cat /sys/class/backlight/$BACKLIGHT/actual_brightness)
	dunstify "Backlight: $((new * 100 / max))%" -r $UNIQUE_ID -a $APP

elif [[ $1 == "-d" ]]; then
	if [[ actual -lt $((max * 11 / 100)) ]]; then
		percentage=2
	elif [[ actual -lt $((max * 31 / 100)) ]]; then
		percentage=5
	else
		percentage=10
	fi

	step=$((max * percentage / 100))
	dec=$((actual - step))
	if [[ $dec -le "0" ]]; then
		dec="1"
	fi
	echo $dec > /sys/class/backlight/$BACKLIGHT/brightness
	new=$(cat /sys/class/backlight/$BACKLIGHT/actual_brightness)
	dunstify "Backlight: $((new * 100 / max))%" -r $UNIQUE_ID -a $APP

fi
