#!/usr/bin/bash

BACKLIGHT="intel_backlight"
UNIQUE_ID=100299
APP=Backlight

max=$(cat /sys/class/backlight/$BACKLIGHT/max_brightness)
step=$((max * $2 / 100))

actual=$(cat /sys/class/backlight/$BACKLIGHT/actual_brightness)

if [[ $1 == "-i" ]]; then
	inc=$((actual + step))
	if [[ $inc -ge $max ]]; then
		inc=$max
	fi
	echo $inc > /sys/class/backlight/$BACKLIGHT/brightness
	new=$(cat /sys/class/backlight/$BACKLIGHT/actual_brightness)
	dunstify "Backlight: $((new * 100 / max))%" -r $UNIQUE_ID -a $APP

elif [[ $1 == "-d" ]]; then
	dec=$((actual - step))
	if [[ $dec -le "0" ]]; then
		dec="1"
	fi
	echo $dec > /sys/class/backlight/$BACKLIGHT/brightness
	new=$(cat /sys/class/backlight/$BACKLIGHT/actual_brightness)
	dunstify "Backlight: $((new * 100 / max))%" -r $UNIQUE_ID -a $APP

fi
