#!/bin/bash

SCALE=1

if [[ -n $1 ]]; then
    SCALE=$1
fi

xrandr --output eDP-1 --auto
xrandr --output eDP-1 --primary
xrandr --output HDMI-1 --auto
xrandr --output HDMI-1 --right-of eDP-1 --scale $SCALE
